#!/usr/bin/env python3
"""Generate T-skills distribution metadata from a single source of truth.

Source of truth:
  - VERSION                            top-level version string (single source)
  - skills/<name>/SKILL.md frontmatter name, description, dispatch_intent

Generated files:
  - .claude-plugin/marketplace.json    full plugin manifest
  - README.md                          install URLs pinned to VERSION
  - package.json                       npm/Pi package metadata pinned to VERSION
  - scripts/setup-rule.sh              default TSKILLS_REF pinned to VERSION
  - scripts/setup-statusline.sh        default TSKILLS_REF pinned to VERSION

Modes:
  --write  (default)  regenerate every file from source
  --check             compare generated bytes against committed files;
                      exit non-zero with a diff on mismatch

Run as: python3 scripts/build_metadata.py [--check] [--root PATH]
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from skill_frontmatter import parse_frontmatter  # noqa: E402


# Hand-maintained marketplace constants. Kept here (not in frontmatter) because
# they describe the T-skills project itself, not any single skill.
MARKETPLACE_TOP = {
    "$schema": "https://anthropic.com/claude-code/marketplace.schema.json",
    "name": "t-skills",
    "description": (
        "Personal skill collection for Claude Code and Codex: think, check, "
        "hunt, design, read, write, learn, and health for agent config and "
        "AI maintainability audits."
    ),
    "owner": {
        "name": "tanglei168",
        "email": "shtangzenglei@gmail.com",
    },
}

BUNDLE_DESCRIPTION = (
    "Installs the full T-skills toolkit. Registers all eight skills under the "
    "t-skills namespace, callable as /t-skills:think, /t-skills:check, /t-skills:hunt, "
    "/t-skills:design, /t-skills:read, /t-skills:write, /t-skills:learn, and /t-skills:health. "
    "For one skill on Claude Code v2.1.143 or newer, use /plugin install "
    "t-skills-<name>@t-skills."
)

CATEGORY = "development"
HOMEPAGE = "https://github.com/tanglei168/T-skills"


def read_version(root: Path) -> str:
    version_file = root / "VERSION"
    if not version_file.exists():
        raise SystemExit(f"ERROR: missing VERSION file at {version_file}")
    version = version_file.read_text().strip()
    if not version:
        raise SystemExit("ERROR: VERSION file is empty")
    return version


def collect_skill_metadata(root: Path) -> list[dict]:
    skill_files = sorted((root / "skills").glob("*/SKILL.md"))
    if not skill_files:
        raise SystemExit("ERROR: no SKILL.md files found under skills/")
    skills: list[dict] = []
    for path in skill_files:
        fields = parse_frontmatter(path)
        if fields["name"] != path.parent.name:
            raise SystemExit(
                f"ERROR: {path} frontmatter name={fields['name']!r} "
                f"!= directory {path.parent.name!r}"
            )
        skills.append(fields)
    return skills


def build_marketplace(version: str, skills: list[dict]) -> dict:
    plugins = [
        {
            "name": "t-skills",
            "description": BUNDLE_DESCRIPTION,
            "version": version,
            "category": CATEGORY,
            "source": "./",
            "homepage": HOMEPAGE,
        }
    ]
    for skill in sorted(skills, key=lambda s: s["name"]):
        plugins.append(
            {
                "name": f"t-skills-{skill['name']}",
                "description": skill["description"],
                "version": version,
                "category": CATEGORY,
                "source": f"./skills/{skill['name']}",
                "homepage": HOMEPAGE,
                # `skills` field declares which subdirectories under `source`
                # contain SKILL.md entrypoints. "./" means the source dir itself
                # is the skill root. Present on every per-skill entry; absent
                # on the bundle (the bundle uses Claude Code's auto-discovery).
                "skills": ["./"],
                "strict": False,
            }
        )
    return {**MARKETPLACE_TOP, "plugins": plugins}


def render_marketplace(marketplace: dict) -> str:
    return json.dumps(marketplace, indent=2, ensure_ascii=False) + "\n"


def build_package_json(version: str) -> str:
    package = {
        "name": "@tanglei168/t-skills",
        "version": version,
        "description": (
            "T-skills engineering skills for Claude Code, Codex, Pi, and "
            "compatible coding agents."
        ),
        "license": "MIT",
        "repository": {
            "type": "git",
            "url": "git+https://github.com/tanglei168/T-skills.git",
        },
        "homepage": "https://github.com/tanglei168/T-skills#readme",
        "keywords": [
            "pi-package",
            "agent-skills",
            "t-skills",
            "claude-code",
            "codex",
        ],
        "files": [
            "LICENSE",
            "README.md",
            "rules",
            "scripts",
            "skills",
            "!**/__pycache__/**",
            "!**/*.pyc",
        ],
        "publishConfig": {
            "access": "public",
        },
        "pi": {
            "skills": [
                "./skills",
            ],
        },
    }
    return json.dumps(package, indent=2, ensure_ascii=False) + "\n"


ROUTING_TABLE_START = "<!-- routing-table:start -->"
ROUTING_TABLE_END = "<!-- routing-table:end -->"


def render_dispatcher(template: str, skills: list[dict]) -> str:
    rows = ["| Intent | Skill | File |", "|--------|-------|------|"]
    for skill in sorted(skills, key=lambda s: s["name"]):
        intent = skill.get("dispatch_intent") or ""
        if not intent:
            raise SystemExit(
                f"ERROR: skill {skill['name']} missing dispatch_intent in frontmatter"
            )
        rows.append(f"| {intent} | {skill['name']} | `skills/{skill['name']}/SKILL.md` |")
    table = "\n".join(rows)
    block = f"{ROUTING_TABLE_START}\n{table}\n{ROUTING_TABLE_END}"
    if ROUTING_TABLE_START not in template or ROUTING_TABLE_END not in template:
        raise SystemExit(
            "ERROR: dispatcher template is missing routing-table markers"
        )
    pattern = re.compile(
        re.escape(ROUTING_TABLE_START) + r".*?" + re.escape(ROUTING_TABLE_END),
        re.DOTALL,
    )
    return pattern.sub(block, template)


# Matches both pinned (v3.24.0) and unpinned (main) install URLs so the
# generator can rewrite either form to the current VERSION.
README_INSTALL_URL_RE = re.compile(
    r"raw\.githubusercontent\.com/tanglei168/T-skills/(?:main|v\d+\.\d+\.\d+)/scripts/"
)
README_SWAP_TAG_RE = re.compile(r"swap `v\d+\.\d+\.\d+` for `main`")
TSKILLS_REF_RE = re.compile(r'TSKILLS_REF="\$\{TSKILLS_REF:-(?:main|v\d+\.\d+\.\d+)\}"')


def render_readme(current: str, version: str) -> str:
    pinned = f"raw.githubusercontent.com/tanglei168/T-skills/v{version}/scripts/"
    current = README_INSTALL_URL_RE.sub(pinned, current)
    return README_SWAP_TAG_RE.sub(f"swap `v{version}` for `main`", current)


def render_script_ref(current: str, version: str) -> str:
    return TSKILLS_REF_RE.sub(f'TSKILLS_REF="${{TSKILLS_REF:-v{version}}}"', current)


def diff(label: str, expected: str, actual: str) -> str:
    return "".join(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"committed:{label}",
            tofile=f"generated:{label}",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=ROOT,
        help="Repository root (default: parent of scripts/)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare generated bytes to committed files; exit non-zero on drift.",
    )
    args = parser.parse_args()
    root = args.root.resolve()

    version = read_version(root)
    skills = collect_skill_metadata(root)
    marketplace = build_marketplace(version, skills)
    rendered = render_marketplace(marketplace)
    package_rendered = build_package_json(version)

    target = root / ".claude-plugin" / "marketplace.json"
    package_json = root / "package.json"
    package_actual = package_json.read_text() if package_json.exists() else ""
    readme = root / "README.md"
    readme_actual = readme.read_text() if readme.exists() else ""
    readme_rendered = render_readme(readme_actual, version)
    ref_scripts = [
        root / "scripts" / "setup-rule.sh",
        root / "scripts" / "setup-statusline.sh",
    ]
    script_pairs = []
    for script in ref_scripts:
        actual = script.read_text() if script.exists() else ""
        script_pairs.append((script, actual, render_script_ref(actual, version)))

    dispatcher_template = root / "scripts" / "dispatcher-template.md"
    dispatcher_target = root / "scripts" / "dispatcher.md"
    if not dispatcher_template.exists():
        raise SystemExit(f"ERROR: missing dispatcher template at {dispatcher_template}")
    dispatcher_actual = (
        dispatcher_target.read_text() if dispatcher_target.exists() else ""
    )
    dispatcher_rendered = render_dispatcher(dispatcher_template.read_text(), skills)

    if args.check:
        actual = target.read_text() if target.exists() else ""
        drift = False
        if actual != rendered:
            print(
                f"DRIFT: {target.relative_to(root)} is out of sync with "
                f"VERSION + SKILL.md frontmatter.\n"
                f"Run scripts/build_metadata.py (no flags) to regenerate.",
                file=sys.stderr,
            )
            sys.stderr.write(diff("marketplace.json", rendered, actual))
            drift = True
        if readme_actual != readme_rendered:
            print(
                f"DRIFT: README.md install URLs are not pinned to v{version}.\n"
                f"Run scripts/build_metadata.py (no flags) to regenerate.",
                file=sys.stderr,
            )
            sys.stderr.write(diff("README.md", readme_rendered, readme_actual))
            drift = True
        if package_actual != package_rendered:
            print(
                f"DRIFT: package.json is out of sync with VERSION v{version} "
                f"and Pi package metadata.\n"
                f"Run scripts/build_metadata.py (no flags) to regenerate.",
                file=sys.stderr,
            )
            sys.stderr.write(diff("package.json", package_rendered, package_actual))
            drift = True
        for script, actual, rendered_script in script_pairs:
            if actual != rendered_script:
                label = script.relative_to(root).as_posix()
                print(
                    f"DRIFT: {label} default TSKILLS_REF is not pinned to v{version}.\n"
                    f"Run scripts/build_metadata.py (no flags) to regenerate.",
                    file=sys.stderr,
                )
                sys.stderr.write(diff(label, rendered_script, actual))
                drift = True
        if dispatcher_actual != dispatcher_rendered:
            label = dispatcher_target.relative_to(root).as_posix()
            print(
                f"DRIFT: {label} routing table is out of sync with "
                f"SKILL.md dispatch_intent frontmatter.\n"
                f"Run scripts/build_metadata.py (no flags) to regenerate.",
                file=sys.stderr,
            )
            sys.stderr.write(diff(label, dispatcher_rendered, dispatcher_actual))
            drift = True
        if drift:
            return 1
        print(f"ok: {target.relative_to(root)} matches generator")
        print(f"ok: README.md install URLs pinned to v{version}")
        print(f"ok: package.json pinned to v{version}")
        print(f"ok: installer defaults pinned to v{version}")
        print(f"ok: {dispatcher_target.relative_to(root)} matches generator")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered)
    print(f"wrote: {target.relative_to(root)} ({len(rendered)} bytes)")
    if package_actual != package_rendered:
        package_json.write_text(package_rendered)
        print(f"wrote: package.json (pinned version to v{version})")
    else:
        print(f"ok: package.json already pinned to v{version}")
    if readme_actual != readme_rendered:
        readme.write_text(readme_rendered)
        print(f"wrote: README.md (pinned install URLs to v{version})")
    else:
        print(f"ok: README.md install URLs already pinned to v{version}")
    for script, actual, rendered_script in script_pairs:
        if actual != rendered_script:
            script.write_text(rendered_script)
            print(f"wrote: {script.relative_to(root)} (default TSKILLS_REF=v{version})")
        else:
            print(f"ok: {script.relative_to(root)} default TSKILLS_REF already pinned")
    if dispatcher_actual != dispatcher_rendered:
        dispatcher_target.write_text(dispatcher_rendered)
        print(
            f"wrote: {dispatcher_target.relative_to(root)} "
            f"({len(dispatcher_rendered)} bytes)"
        )
    else:
        print(f"ok: {dispatcher_target.relative_to(root)} already matches generator")
    return 0


if __name__ == "__main__":
    sys.exit(main())
